import express from 'express';
import { handleCreateProject } from '../controllers/createProject';
import { verifyOwner } from '../middleware/verifyOwner';
import { handleEditProject } from '../controllers/editProject';
import { handleForkProject } from '../controllers/forkProject';
import { handleCreatePR } from '../controllers/pullRequest';
import { handleGetOpenPullRequests } from '../controllers/getPullRequest';
import { handleForkWithHistory } from '../controllers/forkWithHistory';
import { handleGetCommits } from '../controllers/getCommits';
import { handleGetProjectDataWithCommit } from '../controllers/getProjectDataWithCommit';
import { handleGetProjectData } from '../controllers/getProjectData';
import { handleGetProjects } from '../controllers/getProjects';
import { handleCreateBranch } from '../controllers/createBranch';
import { handleSearchProjects } from '../controllers/searchProjects';
import { handleGetProjectDetails } from '../controllers/getProjectDetails';
import { handleGetLikeCount, handleLikeProject } from '../controllers/likeProject';
import { handleGetThumbnail } from '../controllers/getThumbnail';
import { handleDownloadProject } from '../controllers/downloadProject';
import { handlePublishProject } from '../controllers/publishProject';
import { handleReportProject } from '../controllers/reportProject';

const projectRouter = express.Router();

projectRouter.post('/create', handleCreateProject);
projectRouter.post('/fork', handleForkProject);
projectRouter.post('/forkHistory',handleForkWithHistory);
projectRouter.put('/edit', verifyOwner, handleEditProject);
projectRouter.post('/create-pr', handleCreatePR);
projectRouter.get('/openPR',handleGetOpenPullRequests);
projectRouter.get("/commitHistory",handleGetCommits);
projectRouter.get("/getProjectDataAtCommit",handleGetProjectDataWithCommit);
projectRouter.get("/getProjectData",handleGetProjectData);
projectRouter.get("/allRepos",handleGetProjects);
projectRouter.get("/search", handleSearchProjects);
projectRouter.get("/project/:repoName", handleGetProjectDetails);
projectRouter.post("/like", handleLikeProject);
projectRouter.get("/likes/:repoName", handleGetLikeCount);
projectRouter.post('/createBranch', handleCreateBranch);
projectRouter.get("/thumbnail/:repoName", handleGetThumbnail);
projectRouter.get("/download/:repoName", handleDownloadProject);
projectRouter.post("/publish", verifyOwner, handlePublishProject);
projectRouter.post("/report", handleReportProject);

export default projectRouter;
